force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Course Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <description>Name of the course</description>
    <label>Course Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Course__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DepartmentTriggerHandler.cls
public with sharing class DepartmentTriggerHandler {
  public Boolean addDefaultCourse(List<Department__c> departments) {
    List<Course__c> defaultCourses = new List<Course__c>();

    for (Department__c department : departments) {
      Course__c defaultCourse = new Course__c(
        Course_Name__c = 'Default Course for ' + department.Name,
        Department__c = department.Id
      );
      defaultCourses.add(defaultCourse);
    }

    try {
      insert defaultCourses;
      return true;
    } catch (DmlException e) {
      System.debug(LoggingLevel.ERROR, e.getMessage());
      return false;
    }
  }
}